version: '3.9'
services:
  solacenet-dashboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mssql
      - DB_USER=sa
      - DB_PASS=YourStrong!Passw0rd
      - DB_NAME=solacedb
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
